apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
    - name: spark-ui
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: spark-driver
      port: 7077
      targetPort: 7077
      nodePort: 30077
