apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: spark-spark-master
        imagePullPolicy: Never
        env:
        - name: SPARK_MODE
          value: master
        ports:
        - containerPort: 7077
        - containerPort: 8080 